### ISSUE TITLE
jpsvis not found

### ISSUE THREAD

**Issue by SiddharthVarshney** [JuPedSim/jpsvis#78]
After installing all the dependencies and setting up the jpsvis on my system 'ubuntu 18.04', I was trying to run the demo and getting error:
`jpsvis demos/scenario_7_floorfield/Kobes_traj.xml`
`zsh: command not found: jpsvis`

![Screenshot from 2020-01-23 09-38-25](https://user-images.githubusercontent.com/32801674/72956019-362ca000-3dc4-11ea-8926-08dc3e0ee13b.png)
Also, how can I verify that jpsvis is installed on my system or not?
While building the repo using `make` command everything worked fine  

![Screenshot from 2020-01-23 09-36-51](https://user-images.githubusercontent.com/32801674/72956018-362ca000-3dc4-11ea-9bc2-e81e3e2df3b9.png)

**Comment by chraibi** [comment]
Hi @SiddharthVarshney 
after compilation you will find it under `bin`. 
<img width="342" alt="Screenshot 2020-01-24 11 46 28" src="https://user-images.githubusercontent.com/5772973/73063631-86c4fb80-3e9f-11ea-89f6-cadadfa69ea6.png">

(since the screenshot is from a macOS you see .app)

Installation (make install) is not necessary, but is you do then the resulting executable will be in `/tmp/bin`

**Comment by SiddharthVarshney** [comment]
Hi @chraibi 
I just checked ```jpsvis``` is present in the ```bin``` folder.
![Screenshot from 2020-01-24 17-43-51](https://user-images.githubusercontent.com/32801674/73068399-23ec5800-3ed1-11ea-83c2-f0d90bc3750a.png)

How can I run the demo using jpsvis?
Coz running the following command give me the error.

```jpsvis demos/scenario_7_floorfield/Kobes_traj.xml```
```zsh: command not found: jpsvis```

**Comment by chraibi** [comment]
```
./jpsvis demos/scenario_7_floorfield/Kobes_traj.xml
```

(the ./ is important, otherwise your shell is looking for jpsvis a system directory like in /usr/bin or /usr/local/bin

**Comment by SiddharthVarshney** [comment]
@chraibi Thanks it's working now
